[project]
name = "pixistuff"
version = "0.1.0"
description = "Add a short description here"
authors = ["Nathan Glaser <nglaser3@illinois.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
